name: Continuous Integration

on:
    push:
        branches:  # Build 'master' branch
            - 'master'
    pull_request:  # Build any PR

jobs:
  rustfmt:
    name: Formatting check
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest
    steps:
    - uses: actions/checkout@master
    - name: Check formatting
      run: make format
    - name: slack notification (the job has failed)
      if: failure() && github.ref == 'ref/head/master'
      run: |
        curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_CORE_TOOLS_TEAM_URL }}
      env:
        SLACK_TEXT: '{"attachments":[{
        "pretext": "`transit_model CI` requires your attention!",
        "text":" :warning: Formatting check failed!","color":"#D00000",
        "fields":[{"title":"Action URL","value": "https://github.com${{ github.action_path }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]}]}'

  clippy:
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj8.1.0
    steps:
    - uses: actions/checkout@master
    - name: Linting
      run: make lint
    - name: slack notification (the job has failed)
      if: failure() && github.ref == 'ref/head/master'
      run: |
        curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_CORE_TOOLS_TEAM_URL }}
      env:
        SLACK_TEXT: '{"attachments":[{
        "pretext": "`transit_model CI` requires your attention!",
        "text":" :warning: Analyzing code with Clippy failed!","color":"#D00000",
        "fields":[{"title":"Action URL","value": "https://github.com${{ github.action_path }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]}]}'

  audit:
    name: Audits
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj8.1.0
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Security audit
      uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: slack notification (the job has failed)
      if: failure() && github.ref == 'ref/head/master'
      run: |
        curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_CORE_TOOLS_TEAM_URL }}
      env:
        SLACK_TEXT: '{"attachments":[{
        "pretext": "`transit_model CI` requires your attention!",
        "text":" :warning: Audits failed!","color":"#D00000",
        "fields":[{"title":"Action URL","value": "https://github.com${{ github.action_path }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]}]}'

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: kisiodigital/rust-ci:latest-proj8.1.0
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install xmllint
      run: apt update && apt install --yes libxml2-utils
    - name: Run tests with and without features
      run: make test
    - name: slack notification (the job has failed)
      if: failure() && github.ref == 'ref/head/master'
      run: |
        curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_CORE_TOOLS_TEAM_URL }}
      env:
        SLACK_TEXT: '{"attachments":[{
        "pretext": "`transit_model CI` requires your attention!",
        "text":" :warning: Tests failed!","color":"#D00000",
        "fields":[{"title":"Action URL","value": "https://github.com${{ github.action_path }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]}]}'
