name: Publish on dockerhub

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  IMAGE_ID: "navitia/transit_model"
  DOCKER_REGISTRY_URL: docker.io

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_ID

      - name: Tag image
        if: github.event.action == 'published'
        run: |
          VERSION="v$( grep "^version =" Cargo.toml | tr -cd '[:digit:].' )"
          docker tag $IMAGE_ID $IMAGE_ID:$VERSION

      - name: Log into registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login $DOCKER_REGISTRY_URL --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: |
          docker image push --all-tags $IMAGE_ID

      - name: Slack failure notif
        if: failure()
        run: |
          curl -s -X POST -H "Content-Type: application/json" -d '${{ env.SLACK_TEXT }}' ${{ secrets.SLACK_CORE_TOOLS_TEAM_URL }}
        env:
          SLACK_TEXT: '{"attachments":[{
          "pretext": "`transit_model Publish` requires your attention!",
          "text":" :warning: Publish failed!","color":"#D00000",
          "fields":[{"title":"Action URL","value": "https://github.com${{ github.action_path }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]}]}'